### ISSUE TITLE
Fix this

### ISSUE THREAD

**Issue by vaibhavhrt** [IamLizu/react-returnErr-reproduction#1]
https://github.com/IamLizu/react-returnErr-reproduction/blob/9123913e882c7b0c11e57c431a20ebf1a711fbb4/src/components/Yolo.jsx#L42

Replace it with something like:

```jsx
if (secretToken) {
  history.push("greet");
  return null;
}

return (
  <div>
    <button onClick={loginClickHandler}>Login</button>
    <h1>Yolo</h1>
  </div>
);
```

Or better yet, do the history.push in your `loginClickHandler` after successful login and skip all this mess in returning;

**Comment by IamLizu** [comment]
Got it mate, thanks.
